load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_face_mesh_aar",
    calculators = ["//mediapipe/graphs/face_mesh:mobile_calculators"],
)