load("//mediapipe/framework/port:build_config.bzl")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "face_crop_and_align_calculator",
    srcs = ["face_crop_and_align_calculator.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ""
    ]
)
